# Generated by Django 6.0.4 on 2026-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_badge_shopitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='acquisition_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('shop', 'Shop Purchase'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='shop_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
