# Generated by Django 6.0.4 on 2026-04-25 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_badge_acquisition_type_badge_shop_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbadge',
            old_name='earned_at',
            new_name='unlocked_at',
        ),
        migrations.AddField(
            model_name='badge',
            name='required_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='acquisition_type',
            field=models.CharField(choices=[('shop', 'Shop Purchase'), ('automatic', 'Automatic Unlock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
