# Generated by Django 5.2.10 on 2026-01-21 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('seconds', models.PositiveIntegerField()),
                ('milliseconds', models.PositiveIntegerField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('verified', models.CharField(choices=[('Y', 'Verified'), ('N', 'Not Verified')], default='N', max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hours', '-minutes', '-seconds', '-milliseconds'],
            },
        ),
    ]
