# Generated by Django 5.2.10 on 2026-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrun',
            name='video',
            field=models.FileField(default='speedrun_videos/placeholder.mp4', upload_to='Videos/'),
            preserve_default=False,
        ),
    ]
