# Generated by Django 5.2.11 on 2026-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun', '0002_speedrun_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedrun',
            options={'ordering': ['hours', 'minutes', 'seconds', 'milliseconds']},
        ),
        migrations.AddField(
            model_name='speedrun',
            name='game',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='speedrun',
            name='verified',
            field=models.CharField(choices=[('Y', 'Verified'), ('N', 'Not Verified')], default='N', max_length=1),
        ),
    ]
