# Generated by Django 5.2.11 on 2026-03-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun', '0004_alter_speedrun_game_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='speedrun',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='runs', to='speedrun.category'),
        ),
    ]
